version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-goreload
    env_file:
      - .env
    ports:
      - 5000:3000
    volumes:
      - .:/app
    restart: always

  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mockup
      MYSQL_ROOT_PASSWORD: yourPassword
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
   
volumes:
  db_data:
  